language: java
jdk:
  - openjdk15

sudo: false

services:
  - postgresql
before_install:
  - psql -c 'create database ---;' -U postgres

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      oggen18@gmail.com
    on_success: never
    on_failure: always